-- =====================================================================================
-- V1 — BASELINE du schéma Promote
-- =====================================================================================
-- Gelé depuis le schéma que Hibernate générait via `ddl-auto: update` (dialecte PostgreSQL,
-- entités du package com.afriland.promote.model au commit de référence). À partir d'ici le
-- schéma évolue UNIQUEMENT par migrations Flyway versionnées (V2__…, V3__…) et `ddl-auto`
-- passe à `validate`.
--
-- Comportement sur base EXISTANTE (production) : `baseline-on-migrate=true` +
-- `baseline-version=1` font que Flyway POSE un marqueur de baseline et N'EXÉCUTE PAS ce script
-- (la prod garde ses données ; aucune table n'est recréée). Sur une base VIDE (nouvelle install,
-- postgres de CI) ce script crée l'intégralité du schéma. Les `IF NOT EXISTS` sont une ceinture
-- de sécurité supplémentaire.
-- =====================================================================================

create table if not exists action_audit (at timestamp(6) with time zone not null, entity_type varchar(40), action varchar(60) not null, ip varchar(100), actor_id varchar(255), actor_name varchar(255), actor_roles varchar(255), details text, entity_ref varchar(255), id varchar(255) not null, primary key (id));
create table if not exists agency (active boolean not null, created_at timestamp(6) with time zone not null, city varchar(255), id varchar(255) not null, name varchar(255) not null, primary key (id));
create table if not exists app_notification (created_at timestamp(6) with time zone, id bigint generated by default as identity, read_at timestamp(6) with time zone, sender_name varchar(200) not null, title varchar(200) not null, body varchar(2000), recipient_id varchar(255) not null, sender_id varchar(255) not null, image_data TEXT, primary key (id));
create table if not exists app_profile (builtin boolean not null, id bigint generated by default as identity, name varchar(100) not null unique, description varchar(500), permissions varchar(2000), primary key (id));
create table if not exists app_user (enabled boolean default true not null, last_accuracy float(53), last_lat float(53), last_lng float(53), must_change_password boolean default false not null, created_at timestamp(6) with time zone, last_located_at timestamp(6) with time zone, roles varchar(200), agency varchar(255), email varchar(255) not null unique, id varchar(255) not null, login_pin varchar(255), name varchar(255) not null, parent_user_id varchar(255), password_hash varchar(255) not null, phone varchar(255), role varchar(255) not null check (role in ('ADMIN','MANAGER','AGENT','PRINT_AGENT','CASHIER','COLLECTEUR','SUPERVISEUR','CHEF_EQUIPE')), primary key (id));
create table if not exists card_config (fees integer not null, pass_premium integer, pass_premium_bancaire integer, price integer not null, recharge_initiale integer, recharge_initiale_bancaire integer, recharge_max integer, recharge_min integer, transport integer not null, id bigint not null, primary key (id));
create table if not exists collecte (created_at timestamp(6) with time zone not null, account_number varchar(255), card_number varchar(255), card_type varchar(255), client_nom varchar(255), client_phone varchar(255), collected_by_id varchar(255), collected_by_name varchar(255), product varchar(255) not null, ref varchar(255) not null, primary key (ref));
create table if not exists commission_entry (amount integer not null, base_amount integer not null, created_at timestamp(6) with time zone, id bigint generated by default as identity, rule_id bigint, status varchar(12) not null check (status in ('PENDING','VALIDATED','PAID')), sale_type varchar(16) not null check (sale_type in ('SUBSCRIPTION','COLLECTE')), beneficiary_id varchar(40) not null, sale_ref varchar(40) not null, product_code varchar(60) not null, beneficiary_name varchar(255), primary key (id), constraint uk_commission_sale_beneficiary unique (sale_type, sale_ref, beneficiary_id));
create table if not exists commission_rule (active boolean default true not null, end_date date, rate_value integer not null, start_date date, created_at timestamp(6) with time zone, id bigint generated by default as identity, rate_type varchar(10) not null check (rate_type in ('FIXED','PERCENT')), scope_type varchar(10) not null check (scope_type in ('PRODUCT','GROUP')), target_type varchar(10) not null check (target_type in ('ROLE','USER')), scope_code varchar(60) not null, target_value varchar(60) not null, primary key (id));
create table if not exists login_audit (success boolean not null, at timestamp(6) with time zone not null, user_agent varchar(300), email varchar(255), id varchar(255) not null, ip varchar(255), name varchar(255), reason varchar(255), roles varchar(255), user_id varchar(255), primary key (id));
create table if not exists product (active boolean default true not null, base_price integer default 0 not null, builtin boolean default false not null, created_at timestamp(6) with time zone, id bigint generated by default as identity, kind varchar(10) not null check (kind in ('CARD','BANK')), code varchar(60) not null unique, group_code varchar(60), label varchar(120) not null, description varchar(500), primary key (id));
create table if not exists product_component (amount integer not null, id bigint generated by default as identity, product_id bigint not null, ckey varchar(60) not null, label varchar(120), primary key (id));
create table if not exists promotion (active boolean default true not null, end_date date, promo_value integer not null, start_date date, created_at timestamp(6) with time zone, id bigint generated by default as identity, product_id bigint not null, type varchar(10) not null check (type in ('PRICE','PERCENT')), label varchar(120), primary key (id));
create table if not exists recharge (amount integer not null, fulfilled boolean default false not null, gateway_push_accepted boolean not null, geo_accuracy float(53), latitude float(53), longitude float(53), sara_amount integer, cash_collected_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, fulfilled_at timestamp(6) with time zone, paid_at timestamp(6) with time zone, payment_message varchar(500), cash_collected_by varchar(255), cash_collected_by_id varchar(255), evidence_image_key varchar(255), fulfilled_by varchar(255), fulfilled_by_id varchar(255), full_name varchar(255), gateway_ref varchar(255), nom varchar(255), pan varchar(255), pay varchar(255), pay_phone varchar(255), pay_status varchar(255) not null check (pay_status in ('pending','paid','cash','sara_pending','failed')), payment_tx_id varchar(255), phone varchar(255), prenom varchar(255), ref varchar(255) not null, sara_payer_phone varchar(255), sara_receipt_key varchar(255), sara_ref varchar(255), primary key (ref));
create table if not exists subscription (amount integer not null, birth_date date, gateway_push_accepted boolean not null, geo_accuracy float(53), latitude float(53), longitude float(53), printed boolean not null, recharge_amount integer, sara_amount integer, selfie_verified boolean not null, transport integer not null, cash_collected_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, failed_at timestamp(6) with time zone, paid_at timestamp(6) with time zone, printed_at timestamp(6) with time zone, referrer_phone9 varchar(9), payment_message varchar(500), agent_id varchar(255), card_number varchar(255), card_type varchar(255), cash_collected_by varchar(255), cash_collected_by_id varchar(255), cash_payment_reference varchar(255), channel varchar(255), cni varchar(255), cni_exp varchar(255), cni_norm varchar(255), cni_ocr_nom varchar(255), cni_ocr_prenom varchar(255), cni_recto_key varchar(255), cni_verso_key varchar(255), delivery varchar(255), doc_type varchar(255), email varchar(255), full_name varchar(255), gateway_ref varchar(255), niu varchar(255), nom varchar(255), pan varchar(255), pay varchar(255), pay_phone varchar(255), pay_status varchar(255) not null check (pay_status in ('pending','paid','cash','sara_pending','failed')), payment_tx_id varchar(255), phone varchar(255), pickup_agency_id varchar(255), pickup_agency_name varchar(255), prenom varchar(255), printed_by_id varchar(255), quartier varchar(255), ref varchar(255) not null, referrer_name varchar(255), referrer_phone varchar(255), region varchar(255), sara_payer_phone varchar(255), sara_receipt_key varchar(255), sara_ref varchar(255), selfie_key varchar(255), sexe varchar(255), ville varchar(255), primary key (ref));
create table if not exists user_profile (profile_id bigint not null, user_id varchar(255) not null, primary key (profile_id, user_id));

create index if not exists idx_action_audit_at on action_audit (at);
create index if not exists idx_action_audit_actor on action_audit (actor_id);
create index if not exists idx_agency_active on agency (active);
create index if not exists idx_notif_recipient on app_notification (recipient_id);
create index if not exists idx_notif_recipient_unread on app_notification (recipient_id, read_at);
create index if not exists idx_col_product on collecte (product);
create index if not exists idx_col_collected_by_id on collecte (collected_by_id);
create index if not exists idx_col_created_at on collecte (created_at);
create index if not exists idx_comm_beneficiary on commission_entry (beneficiary_id);
create index if not exists idx_comm_product on commission_entry (product_code);
create index if not exists idx_audit_at on login_audit (at);
create index if not exists idx_audit_user_id on login_audit (user_id);
create index if not exists idx_product_group on product (group_code);
create index if not exists idx_pcomp_product on product_component (product_id);
create index if not exists idx_promo_product on promotion (product_id);
create index if not exists idx_rch_pay_status on recharge (pay_status);
create index if not exists idx_rch_created_at on recharge (created_at);
create index if not exists idx_sub_pay_status on subscription (pay_status);
create index if not exists idx_sub_agent_id on subscription (agent_id);
create index if not exists idx_sub_printed_by_id on subscription (printed_by_id);
create index if not exists idx_sub_cash_collected_by_id on subscription (cash_collected_by_id);
create index if not exists idx_sub_created_at on subscription (created_at);
create index if not exists idx_sub_referrer_phone9 on subscription (referrer_phone9);
create index if not exists idx_sub_cni_norm on subscription (cni_norm);

-- Le seul lien référentiel déjà présent dans les entités (table de jointure user ↔ profil).
alter table if exists user_profile add constraint fk_user_profile_profile foreign key (profile_id) references app_profile;
alter table if exists user_profile add constraint fk_user_profile_user foreign key (user_id) references app_user;
